import type { PaletteName } from '../../design/tokens';

export type ViviWorldId = 'apartment_night' | 'hallway_night' | 'bar_or_party' | 'office_night' | 'train_station' | 'city_rain' | 'family_home' | 'hotel_or_rental' | 'neighborhood_sunset' | 'bedroom_night';
export interface WorldSlot { id: string; x: number; y: number; attachment?: 'object' | 'modifier' | 'character'; }
export interface ViviWorldTemplate {
  id: ViviWorldId; label: string; palette: PaletteName;
  layout: string; walkable: [number, number][]; collisions: string[];
  foreground: string[]; background: string[]; lighting: string; atmosphere: string;
  heroCamera: [number, number]; slots: WorldSlot[]; objects: string[];
  shots: [string, string, string];
}
const slot = (id: string, x: number, y: number, attachment: WorldSlot['attachment'] = 'object'): WorldSlot => ({ id, x, y, attachment });
const floor: [number, number][] = [[6, 48], [94, 48], [98, 94], [2, 94]];
export const worldTemplates: Record<ViviWorldId, ViviWorldTemplate> = {
  apartment_night: { id: 'apartment_night', label: 'Apartment · night', palette: 'relationshipNight', layout: 'Living room faces bathroom and hall; phone table cuts the sight line.', walkable: floor, collisions: ['sofa', 'phone_table', 'kitchen_counter', 'window'], foreground: ['sofa arm', 'hanging lamp'], background: ['window', 'kitchen', 'bathroom door', 'hall'], lighting: 'Amber practical against plum window', atmosphere: 'Quiet room tone and shower bleed', heroCamera: [50, 53], slots: [slot('sofa', 25, 72), slot('phone_table', 54, 68), slot('kitchen', 79, 50), slot('bathroom_door', 76, 37, 'modifier'), slot('window', 25, 31), slot('hallway', 91, 56), slot('front_door', 90, 46), slot('bedroom', 12, 52), slot('decision_center', 50, 78, 'character')], objects: ['phone', 'sofa', 'cup', 'lamp', 'door'], shots: ['wide room / separated figures', 'phone insert / amber edge', 'doorway / player foreground'] },
  hallway_night: { id: 'hallway_night', label: 'Hallway · night', palette: 'creepyDomestic', layout: 'Long corridor toward elevator; player door foreground.', walkable: [[10, 47], [92, 47], [92, 89], [10, 89]], collisions: ['door frames', 'stair rail'], foreground: ['near door frame'], background: ['elevator', 'neighbor doors', 'window'], lighting: 'Dirty ceiling practical with cold elevator seam', atmosphere: 'Ventilation and distant motor', heroCamera: [32, 62], slots: [slot('front_door', 18, 63, 'modifier'), slot('elevator', 81, 48, 'modifier'), slot('stairs', 92, 70), slot('camera', 60, 32), slot('intercom', 21, 53, 'modifier'), slot('emergency_light', 62, 24, 'modifier'), slot('window', 46, 30), slot('long_sight_line', 56, 61, 'character')], objects: ['intercom', 'camera', 'door', 'elevator indicator'], shots: ['hallway vanishing point', 'intercom insert', 'handle held in negative space'] },
  bar_or_party: { id: 'bar_or_party', label: 'Bar / party', palette: 'socialTension', layout: 'Crowd center; private edges at exit and quiet corner.', walkable: floor, collisions: ['bar', 'tables', 'crowd cluster'], foreground: ['shoulder silhouettes', 'glassware'], background: ['bar', 'restroom corridor', 'exit'], lighting: 'Warm pools separated by cool pockets', atmosphere: 'Conversation drops out on reveal', heroCamera: [48, 60], slots: [slot('tables', 39, 65), slot('bar', 64, 42), slot('bathroom_corridor', 84, 52), slot('exit', 10, 56, 'modifier'), slot('crowd_clusters', 52, 70, 'character'), slot('phone_area', 35, 74, 'modifier'), slot('quiet_corner', 17, 76)], objects: ['phone', 'glass', 'chair', 'coat'], shots: ['public wide', 'screen over shoulder', 'isolated two shot'] },
  office_night: { id: 'office_night', label: 'Office · night', palette: 'workNight', layout: 'Presentation wall opposes meeting table and laptop evidence.', walkable: floor, collisions: ['meeting table', 'chairs', 'screen'], foreground: ['chair backs'], background: ['city window', 'presentation screen'], lighting: 'Monitor cyan and distant city gold', atmosphere: 'Projector fan and tense silence', heroCamera: [46, 57], slots: [slot('presentation_screen', 52, 29, 'modifier'), slot('director', 70, 58, 'character'), slot('coworker', 40, 45, 'character'), slot('player_laptop', 29, 67, 'modifier'), slot('meeting_clock', 87, 27, 'modifier'), slot('exit', 93, 57)], objects: ['laptop', 'slides', 'clock', 'cup'], shots: ['boardroom wide', 'evidence insert', 'director two shot'] },
  train_station: { id: 'train_station', label: 'Train station', palette: 'memoryWarm', layout: 'Platform edge diagonal; departures board anchors time.', walkable: [[4, 50], [95, 50], [88, 90], [5, 90]], collisions: ['track edge', 'bench', 'column'], foreground: ['column', 'passing commuter'], background: ['train', 'departures board', 'clock'], lighting: 'Honey canopy, cool tracks', atmosphere: 'Brake hiss and departure chime', heroCamera: [44, 59], slots: [slot('station_board', 77, 28, 'modifier'), slot('platform_edge', 65, 73), slot('bench', 21, 65), slot('clock', 42, 25, 'modifier'), slot('train', 84, 47, 'modifier'), slot('exit', 10, 55)], objects: ['ticket', 'bag', 'bench', 'train'], shots: ['platform wide', 'board insert', 'departing silhouette'] },
  city_rain: { id: 'city_rain', label: 'City · rain', palette: 'cityRain', layout: 'Wet diagonal pavement connects shelter and crossing.', walkable: floor, collisions: ['parked car', 'lamp', 'curb'], foreground: ['umbrella', 'rain streak'], background: ['shop windows', 'crosswalk', 'car'], lighting: 'Reflected street amber', atmosphere: 'Rain builds, traffic recedes', heroCamera: [49, 57], slots: [slot('shelter', 18, 58), slot('crossing', 75, 70), slot('street', 53, 76, 'modifier'), slot('car', 78, 51), slot('window', 44, 30, 'modifier')], objects: ['umbrella', 'phone', 'car', 'streetlight'], shots: ['rain wide', 'reflection insert', 'distance two shot'] },
  family_home: { id: 'family_home', label: 'Family home', palette: 'memoryWarm', layout: 'Documents at table; downstairs door stays in frame.', walkable: floor, collisions: ['dining table', 'cabinet'], foreground: ['table edge', 'chair'], background: ['stair door', 'photo wall', 'window'], lighting: 'Afternoon dust with single table lamp', atmosphere: 'House settling, muffled voice below', heroCamera: [46, 59], slots: [slot('documents', 44, 68, 'modifier'), slot('stair_door', 86, 51, 'modifier'), slot('photo_wall', 24, 32), slot('window', 71, 30)], objects: ['document', 'photograph', 'cabinet', 'chair'], shots: ['room wide', 'document insert', 'doorway separation'] },
  hotel_or_rental: { id: 'hotel_or_rental', label: 'Hotel / rental', palette: 'creepyDomestic', layout: 'Entrance opens to an impossible photograph on kitchen table.', walkable: floor, collisions: ['kitchen island', 'bed', 'luggage'], foreground: ['luggage', 'door frame'], background: ['balcony', 'bedroom', 'kitchen'], lighting: 'Overbright rental practical, cold balcony', atmosphere: 'Fridge hum and exterior traffic', heroCamera: [36, 59], slots: [slot('photo', 63, 67, 'modifier'), slot('front_door', 13, 54), slot('kitchen', 65, 53), slot('balcony', 82, 31), slot('bedroom', 28, 37)], objects: ['photo', 'key', 'luggage', 'cup'], shots: ['arrival wide', 'photo insert', 'empty room hold'] },
  neighborhood_sunset: { id: 'neighborhood_sunset', label: 'Neighborhood · sunset', palette: 'memoryWarm', layout: 'Two friends travel past bench toward bus stop.', walkable: floor, collisions: ['bench', 'tree', 'fence'], foreground: ['tree leaves', 'fence'], background: ['rooftops', 'bus stop', 'sky'], lighting: 'Low honey rim through dusty leaves', atmosphere: 'Cicadas and approaching bus', heroCamera: [50, 57], slots: [slot('bench', 24, 66), slot('bus_stop', 82, 54, 'modifier'), slot('tree', 14, 44), slot('path', 53, 76, 'character'), slot('clock', 73, 33, 'modifier')], objects: ['bag', 'bench', 'bus sign', 'tree'], shots: ['street wide', 'walking two shot', 'empty bench hold'] },
  bedroom_night: { id: 'bedroom_night', label: 'Bedroom · night', palette: 'relationshipNight', layout: 'Bed and lit phone separated by a strip of floor.', walkable: floor, collisions: ['bed', 'wardrobe', 'nightstand'], foreground: ['duvet edge'], background: ['window', 'wardrobe', 'door'], lighting: 'Phone light and narrow window spill', atmosphere: 'Breath, fabric and distant road', heroCamera: [47, 58], slots: [slot('bed', 27, 66), slot('phone_screen', 64, 67, 'modifier'), slot('door', 86, 51, 'modifier'), slot('window', 30, 29), slot('nightstand', 66, 59)], objects: ['phone', 'lamp', 'letter', 'bed'], shots: ['room wide', 'phone insert', 'door frame hold'] },
};
