from rig import pose

# yaw 35 = 3/4 facing screen-right. Right arm/leg = near side.
POSES = {
 'neutral': pose(yaw=35, pelvis_roll=-3,
                 legR=dict(flex=4, knee=6, abd=4), legL=dict(flex=-3, abd=4, knee=2),
                 armR=dict(flex=6, abd=5, elbow=14), armL=dict(flex=-4, abd=5, elbow=10)),
 'notice': pose(yaw=75, twist=-38, head_yaw=-95, head_pitch=-8, spine_pitch=-5, support='L', x=0.1,
                legR=dict(flex=16, knee=14, toe=30, turn=0), legL=dict(flex=-8, knee=6),
                armR=dict(flex=18, abd=26, elbow=40, hand='open', curl=0.2), armL=dict(flex=-14, abd=12, elbow=16),
                pelvis_roll=4),
 'listen': pose(yaw=62, spine_pitch=10, head_roll=14, head_pitch=6, neck_fwd=0.6, support='R',
                legR=dict(flex=10, knee=6), legL=dict(flex=-14, knee=16, toe=10),
                armR=dict(flex=20, abd=4, elbow=105, inw=80, hand='relax'),
                armL=dict(flex=16, abd=8, elbow=130, inw=70, hand='relax', curl=0.6)),
 'hesitate': pose(yaw=72, spine_pitch=-9, head_pitch=10, x=-0.1, support='L', pelvis_roll=3,
                  legR=dict(flex=26, knee=4, toe=-18), legL=dict(flex=-8, knee=10),
                  armR=dict(flex=38, abd=6, elbow=58, hand='open', curl=0.3, wrist=-10),
                  armL=dict(flex=20, abd=4, elbow=118, inw=75, hand='fist')),
 'avoid': pose(yaw=50, twist=-125, head_yaw=-25, head_pitch=32, spine_pitch=18, neck_fwd=1.0, support='L', x=-0.2,
               legR=dict(flex=-4, knee=10, turn=-10, abd=8), legL=dict(flex=6, knee=16),
               armR=dict(flex=36, abd=0, elbow=112, inw=88, hand='fist', shrug=1.0),
               armL=dict(flex=34, abd=0, elbow=114, inw=92, hand='fist', shrug=1.0)),
 'turn_toward': pose(yaw=58, twist=-48, head_yaw=-6, head_pitch=-4,
                     legR=dict(flex=10, knee=12, toe=14, turn=30), legL=dict(flex=-8, knee=4, turn=-10),
                     armR=dict(flex=10, abd=16, elbow=20, hand='open', curl=0.2),
                     armL=dict(flex=8, abd=16, elbow=22, hand='open', curl=0.2)),
 'turn_away': pose(yaw=170, twist=8, head_yaw=-28, head_pitch=14, spine_pitch=6,
                   legR=dict(flex=-6, knee=10), legL=dict(flex=8, knee=4),
                   armR=dict(flex=2, abd=4, elbow=30, inw=40), armL=dict(flex=-6, abd=8, elbow=12)),
 'reach': pose(yaw=80, spine_pitch=24, head_pitch=6, support='both', x=0.2,
               legR=dict(flex=36, knee=34), legL=dict(flex=-22, knee=8, toe=30),
               armR=dict(flex=78, abd=4, elbow=6, hand='reach', curl=0.08, wrist=6),
               armL=dict(flex=-24, abd=10, elbow=16)),
 'stop_hand': pose(yaw=70, spine_pitch=-7, head_pitch=-6, support='L',
                   legR=dict(flex=12, knee=4, toe=-10), legL=dict(flex=-10, knee=10),
                   armR=dict(flex=72, abd=4, elbow=22, hand='stop', wrist=75, curl=0.05),
                   armL=dict(flex=-4, abd=8, elbow=40, inw=30)),
 'sit': pose(yaw=55, spine_pitch=-4, head_pitch=4,
             legR=dict(flex=86, knee=92, abd=4), legL=dict(flex=82, knee=84, abd=8, turn=14),
             armR=dict(flex=12, abd=6, elbow=58, hand='rest', curl=0.4),
             armL=dict(flex=10, abd=10, elbow=55, hand='rest', curl=0.4), seat=True),
 'stand': pose(yaw=60, spine_pitch=44, head_pitch=-16, neck_fwd=0.4,
               legR=dict(flex=64, knee=78, abd=5), legL=dict(flex=58, knee=74, abd=8),
               armR=dict(flex=50, abd=6, elbow=40, hand='rest'), armL=dict(flex=46, abd=8, elbow=36, hand='rest'), seat=True),
 'raise_hand': pose(yaw=30, head_pitch=-12, spine_roll=-4, pelvis_roll=-3,
                    legR=dict(flex=3, knee=4), legL=dict(flex=-2, knee=6),
                    armR=dict(flex=168, abd=8, elbow=16, hand='open', curl=0.15),
                    armL=dict(flex=0, abd=6, elbow=14)),
 'speak': pose(yaw=40, spine_pitch=6, head_pitch=-6, head_yaw=-8,
               legR=dict(flex=12, knee=8), legL=dict(flex=-10, knee=6),
               armR=dict(flex=26, abd=24, elbow=78, hand='open', curl=0.2, wrist=10, inw=-30),
               armL=dict(flex=18, abd=10, elbow=70, hand='open', curl=0.3, inw=10)),
 'wait': pose(yaw=22, pelvis_roll=-10, spine_roll=6, head_roll=-10, head_pitch=4, x=0.15, support='R',
              legR=dict(flex=0, abd=7, knee=0), legL=dict(flex=10, abd=-16, knee=20, toe=30, turn=-24),
              armR=dict(flex=-8, abd=24, elbow=42, inw=40, hand='pocket', shrug=0.3),
              armL=dict(flex=-8, abd=24, elbow=42, inw=40, hand='pocket', shrug=0.3)),
 'leave': pose(yaw=150, spine_pitch=8, head_pitch=14,
               legR=dict(flex=26, knee=12), legL=dict(flex=-24, knee=24, toe=34),
               armR=dict(flex=-22, abd=6, elbow=16), armL=dict(flex=22, abd=6, elbow=26)),
 'return': pose(yaw=-25, spine_pitch=10, head_pitch=26, neck_fwd=0.7,
                legR=dict(flex=12, knee=10), legL=dict(flex=-10, knee=20, toe=18),
                armR=dict(flex=-4, abd=3, elbow=12, shrug=-0.2, curl=0.5),
                armL=dict(flex=10, abd=3, elbow=16, shrug=-0.2, curl=0.5)),
 'freeze': pose(yaw=30, spine_pitch=-3, head_pitch=-10, head_yaw=20,
                legR=dict(flex=22, knee=6, toe=-12, abd=6), legL=dict(flex=-20, knee=20, toe=30, abd=4),
                armR=dict(flex=14, abd=40, elbow=18, hand='open', curl=0.15, spread=1),
                armL=dict(flex=-6, abd=38, elbow=14, hand='open', curl=0.15, spread=1)),
 'lower_gaze': pose(yaw=30, spine_pitch=14, head_pitch=40, neck_fwd=1.0,
                    legR=dict(flex=2, knee=6, abd=1, turn=-4), legL=dict(flex=-1, knee=6, abd=1, turn=-4),
                    armR=dict(flex=18, abd=0, elbow=42, inw=70, hand='clasp', shrug=0.5),
                    armL=dict(flex=18, abd=0, elbow=44, inw=75, hand='clasp', shrug=0.5)),
 'look_at': pose(yaw=70, twist=6, head_yaw=4, head_pitch=-2, spine_pitch=2,
                 legR=dict(flex=6, knee=6), legL=dict(flex=-6, knee=4),
                 armR=dict(flex=4, abd=4, elbow=24), armL=dict(flex=2, abd=6, elbow=14)),
 'phone': pose(yaw=40, spine_pitch=8, head_pitch=34, neck_fwd=0.9, phone=True,
               legR=dict(flex=4, knee=8), legL=dict(flex=-4, knee=4),
               armR=dict(flex=26, abd=2, elbow=112, inw=40, hand='phone'),
               armL=dict(flex=24, abd=4, elbow=104, inw=60, hand='grip')),
 'lean_in': pose(yaw=60, spine_pitch=34, head_pitch=-8, neck_fwd=0.5,
                 legR=dict(flex=84, knee=96, abd=4), legL=dict(flex=80, knee=88, abd=8, turn=10),
                 armR=dict(flex=56, abd=6, elbow=58, hand='rest', inw=30),
                 armL=dict(flex=52, abd=8, elbow=62, hand='rest', inw=40), seat=True),
}

POSES['walk'] = pose(yaw=82, spine_pitch=3, legR=dict(flex=24, knee=8), legL=dict(flex=-20, knee=22, toe=26),
                     armR=dict(flex=-16, abd=4, elbow=20), armL=dict(flex=18, abd=4, elbow=24))

LABELS = {
 'neutral': ('Neutral', 'Weight on the back leg, arms fall with gravity. The baseline everything returns to.'),
 'notice': ('Notice', 'Head turns past the shoulder; front heel lifts. The body hasn\'t agreed yet.'),
 'listen': ('Listen', 'Weight forward, head tilts, one arm folds and holds the other.'),
 'hesitate': ('Hesitate', 'Torso pulls back over the rear foot while one forearm stays out in the air.'),
 'avoid': ('Avoid', 'Hips stay, chest twists away, shoulders up, arms locked over the chest.'),
 'turn_toward': ('Turn toward', 'Chest opens square to the target; the feet are still catching up.'),
 'turn_away': ('Turn away', 'The back becomes the message. Head drops a little, no face.'),
 'reach': ('Reach', 'Hinge from the hip, back leg on its toe; the hand leads the arm.'),
 'stop_hand': ('Stop hand', 'Palm vertical at chest height, body leaning away from its own hand.'),
 'sit': ('Sit', 'Upright, hands resting on thighs. The chair is part of the pose.'),
 'stand': ('Stand (rise)', 'The rise, not the result: weight over the knees, hands pushing off.'),
 'raise_hand': ('Raise hand', 'One arm straight up, body tilts away from it. The loudest silhouette.'),
 'speak': ('Speak', 'Hands open and come forward; small lean. No mouth, never lip-sync.'),
 'wait': ('Wait', 'Hip out, free foot crossed, hands pocketed so the elbows open. Time passing in the body.'),
 'leave': ('Leave', 'Back three-quarter, long stride, head down. Arms swing, nothing reaches.'),
 'return': ('Return', 'Toward camera, short stride, shoulders dropped, gaze on the floor.'),
 'freeze': ('Freeze', 'Caught mid-step. Arms lift off the body and stay there.'),
 'lower_gaze': ('Lower gaze', 'Head falls forward, upper back rounds, hands clasp low.'),
 'look_at': ('Look at another', 'Profile, square to the other person. Distance does the acting.'),
 'phone': ('Look at phone', 'Hands meet at the chest; head drops into the light.'),
 'lean_in': ('Lean in (seated)', 'Seated, forearms toward the table, head forward of the knees.'),
}
ORDER = ['neutral', 'notice', 'listen', 'hesitate', 'avoid', 'turn_toward', 'turn_away',
         'reach', 'stop_hand', 'sit', 'stand', 'raise_hand', 'speak', 'wait',
         'leave', 'return', 'freeze', 'lower_gaze', 'look_at', 'phone', 'lean_in']
