/**
 * Build THE CORRECTION's runtime geometry from the approved Design r4 package.
 *
 *   node --import tsx scripts/build-v3-correction-geometry.ts           write src/data/.../theCorrection.geometry.ts
 *   node --import tsx scripts/build-v3-correction-geometry.ts --check   fail if the committed module is not a fresh build
 *
 * Offline and deterministic: pinned input bytes in (scripts/lib/correctionGeometryBuild.ts), one generated module
 * out, then the compiled manifests, the geometry resource and every selectable framing are validated by the real
 * runtime validators (scripts/lib/correctionGeometryValidate.ts). Nothing here is hand-maintained geometry.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildCorrectionGeometry, PINNED, type CorrectionGeometryBuild } from './lib/correctionGeometryBuild.ts';

const ROOT = resolve(import.meta.dirname, '..');
export const GENERATED = 'src/data/experienceV3Fixtures/runtime/theCorrection.geometry.ts';
const ASSET_BASE = 'docs/visual-v3/correction-slice/';

export function readInputs() {
  return {
    source: readFileSync(resolve(ROOT, PINNED.source.path)),
    audit: readFileSync(resolve(ROOT, PINNED.audit.path)),
    assets: readFileSync(resolve(ROOT, PINNED.assets.path)),
  };
}

/** The generated module's exact text. Asset paths become bundler-resolved URLs, relative to the module. */
export function emit(b: CorrectionGeometryBuild): string {
  const json = (v: unknown) => JSON.stringify(v, null, 1).replace(/"@@asset:([^"@]+)@@"/g, (_m, p: string) => `new URL(${JSON.stringify(`../../../../${ASSET_BASE}${p}`)}, import.meta.url).href`);
  return `/**
 * GENERATED by scripts/build-v3-correction-geometry.ts — do not edit. Rebuild: node --import tsx scripts/build-v3-correction-geometry.ts
 *
 * THE CORRECTION · runtime geometry compiled from Design ${b.provenance.sourceRevision} (design/vivi-v3-correction-slice @ ${b.provenance.designCommit}).
 * source.json sha256 ${b.provenance.sourceSha256}
 * collision_audit.json sha256 ${b.provenance.auditSha256}
 * assets.json (${b.provenance.assetsRevision}) sha256 ${b.provenance.assetsSha256}
 *
 * One coordinate authority: marks and routes below are carried into the manifest's compiled scenes by
 * compileFixturePlan; the resource carries floor, collision, occluders, doors, anchors and cameras; staging carries
 * presentation only (framings, plates, islands, postures). Public, pre-boundary: no reveal material.
 */

import type { RuntimeGeometryV3 } from '../../../engine/v3/contracts/geometry.ts';
import type { StagingV3 } from '../../../components/experience/v3/staging.ts';
import type { GeometryExport } from './compileFixturePlan.ts';

export const CORRECTION_GEOMETRY_PROVENANCE = ${json(b.provenance)} as const;

export const CORRECTION_RUNTIME_GEOMETRY: Record<'rich' | 'compressed', RuntimeGeometryV3> = ${json(b.geometry)};

export const CORRECTION_GEOMETRY_EXPORTS: Record<'rich' | 'compressed', GeometryExport> = ${json(b.exports)};

export const CORRECTION_STAGING: Record<'rich' | 'compressed', StagingV3> = ${json(b.staging)};
`;
}

async function main() {
  const check = process.argv.includes('--check');
  const built = buildCorrectionGeometry(readInputs());
  const text = emit(built);
  const target = resolve(ROOT, GENERATED);
  if (check) {
    let committed = '';
    try {
      committed = readFileSync(target, 'utf8');
    } catch {
      /* missing */
    }
    if (committed !== text) {
      console.error(`${GENERATED} is not a fresh build of the pinned Design inputs. Run: node --import tsx scripts/build-v3-correction-geometry.ts`);
      process.exit(1);
    }
  } else writeFileSync(target, text);
  const { validateCorrectionGeometry } = await import('./lib/correctionGeometryValidate.ts');
  const issues = await validateCorrectionGeometry();
  if (issues.length) {
    console.error(`Compiled geometry failed validation:\n  ${issues.join('\n  ')}`);
    process.exit(1);
  }
  const g = built.geometry.rich;
  console.log(`${check ? 'Checked' : 'Wrote'} ${GENERATED}: ${g.locations.length} locations, ${g.cameras.length} camera recipes, ${built.audit.length} audit checks reproduced, source ${built.provenance.sourceSha256.slice(0, 12)}`);
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
